package constant

const (
	PARKING_STATUS_AVAILABLE   = "AVAILABLE"
	PARKING_STATUS_BOOKED      = "BOOKED"
	PARKING_STATUS_MAINTENANCE = "MAINTENANCE"

	BOOK_STATUS_ON_GOING = "ON_GOING"
	BOOK_STATUS_FINISHED = "FINISHED"
)
